# Copyright (c) 2019-present, DIEGO DAGUM.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

cxx_binary(
  name = 'main',
  srcs = [
    'main.cpp',
  ],
  deps = [
    '//src:bitsetiter',
  ]
)
