# Copyright (c) 2019-present, DIEGO DAGUM.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

cxx_library(
  name = 'bitsetiter',
  header_namespace = 'bitset',
  srcs = glob(['*.c', '*.cc', '*.cpp', '*.cxx']),
  exported_headers = ['bitset_iter.h'],
  visibility = [
    'PUBLIC',
  ],
)
